Raise minimum tested compiler to 1.70
Required by clap 4.4.0.

    error: package `clap v4.4.0` cannot be built because it requires rustc
    1.70.0 or newer, while the currently active rustc version is 1.65.0
    Either upgrade to rustc 1.70.0 or newer, or use
    cargo update -p clap@4.4.0 --precise ver
    where `ver` is the latest version of `clap` supporting rustc 1.65.0