Raise minimum toolchain to rust 1.65
Required by use of let-else in the db-dump crate.

    error[E0658]: `let...else` statements are unstable
      --> github.com-1ecc6299db9ec823/db-dump-0.4.1/src/date.rs:42:13
       |
    42 | /             let Some(naive_date) = ({
    43 | |                 NaiveDate::from_ymd_opt(year as i32, month as u32, day as u32)
    44 | |             }) else {
    45 | |                 break;
    46 | |             };
       | |______________^

    error[E0658]: `let...else` statements are unstable
      --> github.com-1ecc6299db9ec823/db-dump-0.4.1/src/datetime.rs:43:13
       |
    43 | /             let Some(naive_date) = ({
    44 | |                 NaiveDate::from_ymd_opt(year as i32, month as u32, day as u32)
    45 | |             }) else {
    46 | |                 break;
    47 | |             };
       | |______________^

    error[E0658]: `let...else` statements are unstable
      --> github.com-1ecc6299db9ec823/db-dump-0.4.1/src/datetime.rs:79:13
       |
    79 | /             let Some(naive_time) = ({
    80 | |                 NaiveTime::from_hms_micro_opt(hour as u32, min as u32, sec as u32, micro)
    81 | |             }) else {
    82 | |                 break;
    83 | |             };
       | |______________^