Ignore buggy mismatching_type_param_order clippy lint
https://github.com/rust-lang/rust-clippy/issues/8962

    error: `Collection` has a similarly named generic type parameter `R` in its declaration, but in a different order
      --> src/max.rs:22:65
       |
    22 | impl<G, K, V, R> MaxByKey<G, K, V, R> for Collection<G, (K, V), R>
       |                                                                 ^
       |
       = note: `-D clippy::mismatching-type-param-order` implied by `-D clippy::pedantic`
       = help: try `D`, or a name that does not conflict with `Collection`'s generic params
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mismatching_type_param_order